apiVersion: v1
kind: Service
metadata:
  name: netflix-support
spec:
  selector:
    app: netflix-support
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

